apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: "879772956301.dkr.ecr.ca-central-1.amazonaws.com/user10-gateway:latest"
          ports:
            - containerPort: 8080
